version: '3.9'
services:
  app:
     container_name: mytheresa-app
     build:
       context: .
       dockerfile: ./deploy/docker/mytheresa/app.Dockerfile
     ports:
       - 8080:8080
     volumes:
       - .:/var/www/html 
     env_file:
       - .env                  
     depends_on:
      db:
        condition: service_healthy   
      redis:
        condition: service_healthy
     networks:
      - mytheresa-network
 
  db:
    container_name: mytheresa-mysql
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mytheresa
      MYSQL_PASSWORD: mytheresa
      MYSQL_DATABASE: mytheresa
    ports:
      - 3306:3306
    networks:
      - mytheresa-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:                        
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s                       
      timeout: 5s                       
      retries: 5                         
      start_period: 30s  

  redis:
    container_name: mytheresa-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mytheresa-network
    healthcheck:                          
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s                        
      timeout: 5s                        
      retries: 5                         
      start_period: 30s 


volumes:
  mysql-data:
  redis_data:


networks:
  mytheresa-network: